In [9]:
import numpy as np


In [10]:
arr = np.array([1, 2, 3, 4, 5])
result = arr**3  #vectorized operation
print(result)

[  1   8  27  64 125]


In [11]:
result + 10

array([ 11,  18,  37,  74, 135])

In [12]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])
result = arr1 + arr2  # Broadcasting arr2 across arr1
print(result)

[[2 4 6]
 [5 7 9]]


# Normalization


In [13]:
data = np.array([[10, 20, 30], [15, 25, 35], [20, 30, 40], [25, 35, 45], [30, 40, 50]])

In [14]:
mean = data.mean(axis=0)
std = data.std(axis=0)

In [15]:
normalized_data = (data - mean) / std

In [16]:
print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
