In [2]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]])

In [3]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [4]:
flat = arr.flatten()

In [5]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [6]:
flat[0]

np.int64(1)

In [7]:
flat[3: 6]

array([4, 5, 6])

In [8]:
flat[:5] 

array([1, 2, 3, 4, 5])

In [9]:
flat[3:13] # same as flat[0:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [10]:
flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [11]:
flat


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [12]:
b = flat[3:7].copy() #this not a slice because we are using copy method to get the copy

In [13]:
b


array([4, 5, 6, 7])

In [14]:
b[0] = 4444446666

In [15]:
b

array([4444446666,          5,          6,          7])

In [16]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [17]:
# Fancy indexing
arr = np.array([1, 54, 23, 53, 2, 3, 34, 5, 6])

In [18]:
arr[[1, 4, 6]]

array([54,  2, 34])

In [19]:
arr[arr>3]

array([54, 23, 53, 34,  5,  6])

In [20]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [21]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr1.shape

(3, 3)

In [23]:
arr2 = np.array([1.1, 2.2, 3.3])

In [24]:
arr2

array([1.1, 2.2, 3.3])

In [25]:
arr2.dtype

dtype('float64')

In [26]:
arr2_int = arr2.astype(np.int64)

In [27]:
arr2_int

array([1, 2, 3])

In [28]:
arr3 = np.array([1, 2, 3, 4, 5, 6])

In [29]:
arr3

array([1, 2, 3, 4, 5, 6])

In [30]:
arr3[[1,3,5]]

array([2, 4, 6])

In [31]:
arr4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,])

In [32]:
arr4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr4.reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

ValueError: cannot reshape array of size 9 into shape (3,5)