In [3]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [4]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr[0]

array([1, 2, 3])

# axis=0 represent rows
np.sum(arr, axis=0)

In [6]:
# axis=1 represnt columns
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [7]:
arr[0][1]

np.int64(2)

In [8]:
arr[0, 1]

np.int64(2)

In [9]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [10]:
arr3d = np.array([
    [[1, 2, 3], [4, 5, 6]], 
    
    [[7, 8, 9], 
     [10, 11, 12]]])

In [11]:
arr3d


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
print(arr3d[:, 0, :])

[[1 2 3]
 [7 8 9]]


In [13]:
arr3d[:, 0, :] = 0

In [14]:
arr3d

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])